### ISSUE TITLE
Add a README.md to briefly introduce our Cap2Det approach.

### ISSUE THREAD

**Issue by yekeren** [yekeren/Cap2Det#1]

**Comment by WZHsmile** [comment]
But there is nothing in it ,Would you please add somethiong to Readme.md?

**Comment by zhmd** [comment]
Sorry, we were busy with something else; we'll add a readme document soon. 
In the meantime, feel free to check out our paper at https://arxiv.org/abs/1907.10164.
Sorry about the inconvenience.

**Comment by yekeren** [comment]
I updated the README.md to shall how to use the code.
